### ISSUE TITLE
ES5 vs ES6

### ISSUE THREAD

**Issue by beverts312** [swellaby/generator-swell#15]
@swellaby/core-collaborators 
Do you guys see any problems with targeting ES6 instead of ES5 in the boilerplate tsconfig?  
Then we could drop q from the VSTS generator and use native promises instead

**Comment by calebcartwright** [comment]
@beverts312 I must confess, I haven't done any hands on work with ES6 yet but I'm open to it. What impacts could this have? For example: 

- would it require adding a babel/traceur? 
- would it require any polyfills? 
- Will mocha/chai still work for testing or will it require additional/different libraries? 
- Do the es6 promises have the support for node that allows functions to support both promises and callbacks simultaneously? i.e. promise.nodify(....) - this is more of a question of curiosity than anything as I don't think a vsts task falls into the same bucket as an API/library that would be reused elsewhere

**Comment by calebcartwright** [comment]
hell for that matter, does anyone know if the latest version of typescript has async/await? If not it should be there soon

**Comment by beverts312** [comment]
* When using targeting ES6 I have never had to explicitly add anything extra  
* I am not sure about polyfills  
* Mocha/Chai have worked the same in my experience  
* I don't think it supports that  

From [this page](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-17) it looks like async/await is supported in ES6

**Comment by calebcartwright** [comment]
But will VSTS/the VSTS build agent support ES6? my guess is that one way or another we will ultimately have to get down to ES5. could be a question for Sam though. I bet he knows someone who knows!

**Comment by beverts312** [comment]
It works on VSTS, I have been using it [here](https://github.com/beverts312/vsts-build-tasks/tree/master/cloudformation-deploy)

**Comment by beverts312** [comment]
Also just tried async/await locally, works pretty sexylike

**Comment by calebcartwright** [comment]
awesome! lets go for it. This is what I was looking for on TS - https://blog.mariusschulz.com/2016/12/09/typescript-2-1-async-await-for-es3-es5 

Looks like we can use async/await for all targets now. Want to try those vs. promises? Will be new, but I imagine pretty excellent

**Comment by beverts312** [comment]
Ya, after I verify how it looks in unit tests ;)
It definitely produces cleaner looking code

**Comment by calebcartwright** [comment]
Need to update the helper.ts file to remove the references to Q and move to async/await or ES6 promises

@beverts312 should we use this issue to track, or create a new one?

**Comment by beverts312** [comment]
Ahh good call, letso stick with this one

**Comment by beverts312** [comment]
good to close this?

**Comment by calebcartwright** [comment]
let me compare what you have to the changes I made first

**Comment by calebcartwright** [comment]
changes merged together, conflicts, resolved, and merged into master. will close this as soon as the build on master completes

**Comment by calebcartwright** [comment]
and done!
