### ISSUE TITLE
Automated Functional Tests

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#18]
@swellaby/core-collaborators - I think one of the next big focuses should be on a suite of automated functional tests. I've discovered throughout this process that testing of Yeoman generators is a bit different than a typical node.js codebase. For example, the "unit" tests are done with a specialized yeoman testing framework, but under the hood this framework actually executes part of the generator within a temporary directory and then cleans it up. 

Our unit tests are providing us with verification that the generator is scaffolding the correct things, but it doesn't tell us whether the things that are scaffolded function correctly. For example, our unit tests ensure that the correct gulp task files are created but we don't currently have an automated way to verify that those generated gulp tasks correctly perform their function (lint, test, etc.)

I typically like using shelljs (along with mocha of course) to run functional tests against node cli apps (like yo) so that is going to be my recommendation here.

Thoughts? Objections?

**Comment by beverts312** [comment]
sounds good to me

**Comment by calebcartwright** [comment]
still need to do this, but I recommend punting it from the 1.0 release. we already have IMO a surprisingly regular number of downloads on npm so I recommend we focus on knocking out the existing bugs/issues and focus on enhancing the pipeline with tests immediately after.

@beverts312 thoughts or concerns?

**Comment by calebcartwright** [comment]
Punting this to 2.x as our suite of both unit and component tests are sufficient for the release pipeline for 1.x

**Comment by calebcartwright** [comment]
No longer in scope given deprecation plans, refs #249
