### ISSUE TITLE
Add License support like npm init Functionality

### ISSUE THREAD

**Issue by beverts312** [swellaby/generator-swell#28]
Currently we populate the name & description fields of the package.json.  
Here are the prompts provided by npm init:  
```
name: () 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
```  
I think we should add prompts for author and license.  
I think we can default the values of some of the other fields and no ask about them in the generator.  
Thoughts?

**Comment by calebcartwright** [comment]
Author definitely, license I am thinking no. Author because it's a value that will be needed in multiple places, but license just adds another layer that I don't feel like dealing with. Granted, I haven't used that many yo generators, but I don't recall any of them asking me about license

**Comment by calebcartwright** [comment]
I retract my former comment :) License support would be good to have, just a matter of whether or not we think it needs to go in as part of 1.0 release.

**Comment by beverts312** [comment]
I think this should be post 1.0

**Comment by calebcartwright** [comment]
I forgot this issue originally covered both the license and author. We have a separate issue now to track author in #47 (which is necessary for v1.0) so I am going to change this issue to focus on license support, and will take it out of consideration for v1.0

**Comment by calebcartwright** [comment]
Could use this [license generator](https://github.com/jozefizso/generator-license) via yeoman composition to add license support without too much heavy lifting on our side

**Comment by calebcartwright** [comment]
No longer in scope given deprecation plans, refs #249
