### ISSUE TITLE
Linters ESLint vs. JSHint vs. Both

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#38]
Currently the generator scaffolds out support for three linters in new projects: TSLint, ESLint, and JSHint. While I think it is important to support linting of the source TypeScript as well as the emitted JavaScript (lots of reasons, can discuss if needed) I am now seriously questioning if we should continue to have the generator supply *two* linters for the JS. 

I am thinking/proposing we update the generator to just provide ESLint and no longer include JSHint in created projects. Here's why:

- JSHint has been a real PITA to work with the types of content in the generated projects (TypeScript async/await, ES6 promises, etc.) In contrast, it only took a couple of minutes to update the ESLint rule configurations to account for this
- JSHint used to contain more features (to support style checks for example) but that was deprecated in lieu of JSCS, which ultimately folded/merged with ESLint. ESLint today provides a one stop shop for what JSCS/JSHint paired together used to provide. With ESLint in place, our JSHint step is essentially just executing half of the ESLint rules twice
- ESLint has some nicer mechanisms. For example in-line/in-file support to disable then re-enable a rule using the same global config values as opposed to JSHint which requires inline rule tweaks to reset the value of the rule in line.
- ESLint has more flexibility in the configuration for warnings vs. errors etc.

Thoughts @beverts312 or anyone else?

**Comment by calebcartwright** [comment]
Another reason: ESLint prints out the rulename whenever an issue is encountered by default. This makes it super easy to figure out what was flagged and why, and allows users to adjust as needed. JSHint requires you modify the output configuration to 'verbose', and even then it only displays a semi-random code (ex W035) that isn't tied to the actual rule in any discernable way. This leads to a lot of googling back and forth just to try to figure out the rule is.

**Comment by beverts312** [comment]
@calebcartwright agreed that having both of them is redundant, seems like ESHint is the one to keep

**Comment by calebcartwright** [comment]
@traviskosarek now that you appear to be active here, do you have any strong objections to the removal of JSHint?
