### ISSUE TITLE
Create Contributing guidelines

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#40]
Should build out some real docs on contributions (both PRs and opening issues), at least something more than my simple sarcasm currently in the contributing.md file :)

**Comment by beverts312** [comment]
I like the [Docker Contributing Guidelines](https://github.com/docker/docker/blob/master/CONTRIBUTING.md) as something to base ours off of

**Comment by calebcartwright** [comment]
def looks like a good reference
