### ISSUE TITLE
Update CLI project type prompt for 1.0 Release

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#41]
I think it is fair to say at this point that the support for the front end project types (Angular, Aurelia, etc.) won't be in the 1.0 release, but what about the CLI project type? 

It is the only type that exist in the currently displayed prompt options that is 100% empty. Will either need to implement it or remove it from the list (which entails updating the corresponding tests)

**Comment by beverts312** [comment]
I'd say we could remove it, unless you need a CLI for something soon

**Comment by calebcartwright** [comment]
I don't know of any immediate use for it. The only reason I am going back and forth mentally is because I believe it'll be the smallest/easiest of all the types. I might do a little spike activity to see what it looks like, and if it is anything significant then will punt it to a subsequent release

**Comment by calebcartwright** [comment]
I was thinking about this one earlier, and thought that if we decide to exclude this from 1.0 then the easiest way we could update the current codebase would be to add a message to indicate the status to both the relevant docs, as well as the generator prompt text. For example, add something like (not yet supported) to the display text to the prompt option. This would only require an update to the expected title in the tests and the rest of the code could stay in place as is.

@beverts312 thoughts?

**Comment by beverts312** [comment]
that sounds like a good gap solution

**Comment by calebcartwright** [comment]
Will pull this into the v1.0 milestone on the simple gap fix discussed here
