### ISSUE TITLE
Setup Deployment Pipeline

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#42]
self explanatory

**Comment by beverts312** [comment]
Are you planning on using VSTS for this?

**Comment by calebcartwright** [comment]
absolutely

**Comment by calebcartwright** [comment]
@beverts312 the framework for this is in place in VSTS. The big decision points we have:

- when to package the repo
- where to publish the module (VSTS, npm) 
- how to handle module versions that fail tests
- when to create git tags and push back to github

some possible scenarios I see

1. build in VSTS on master (triggered or manual, can decide that later) that clones, unit + component tests, tag and send to GitHub, package and publish to npmjs. have triggered release definition that does an npm install on the various environments to run functional tests, etc. if everything passes do nothing, if tests fails then remove that version from npmjs and delete the git tag
2. same as 1 but publish to a VSTS package feed, use that location for testing, and then if all tests pass (somehow) promote/publish that version to npmjs
3. build again as usual, but don't tag or package. publish the whole workspace through VSTS and use that as the artifact in the subsequent environments. pick a variety of options for doing a global npm "install" (or link or etc.) of that on each test environments all the way through. for the last stage add a git init (to add and push the tag) and a package and publish to npmjs 

I think theres a lot of variations on the above, and probably additional options as well. Thoughts?

**Comment by beverts312** [comment]
1 definitely seems like the best option to me, if that got to complex I think 3 is sufficient.   
Also 3 could be a gap solution until we want to put the time into 1

**Comment by calebcartwright** [comment]
just realized I've had this one in TODO for 4+ months now :(

**Comment by calebcartwright** [comment]
Finished, finally :)
