### ISSUE TITLE
Shrinkwrap support?

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#44]
Should we have the generator leverage npm's  shrinkwrap for the scaffolded projects? I'm leaning towards no (current state), but we should make a decision on it prior to 1.0 release 

The pros I see for shrinkwrap:

- easier debugging/support since we will know the specific version of each package in the dependency tree for each version of the generator we release
- could address the warnings currently displayed during an npm install of a generated project due to node-uuid being used somewhere in the dep. tree (not a direct dependency)

The major con I see is that it makes dependency management a real pain. We will have to very consciously follow and update package versions or do a lot of back and forth removal/recreation of the shrinkwrap file

**Comment by beverts312** [comment]
seems like alot of effort for not much reward

**Comment by calebcartwright** [comment]
good enough for me
