### ISSUE TITLE
Refactor Tests

### ISSUE THREAD

**Issue by beverts312** [swellaby/generator-swell#53]
`index-tests.js` is becoming too large to manage. We should refactor it into separate files.
We should also consider refactoring `index.js` to be more files. I think thats a discussion we should tie into this issue because it may impact our strategy for refactoring the tests.

@swellaby/core-collaborators What do yall think?

**Comment by calebcartwright** [comment]
Lets do it, but prior to the tests we need determine how the app code may or may not change as part of the refactoring to typescript. If the index.js (TS) is going to be split out then that will have significant impact on how the tests are structured (a lot of passing around the yo context, etc.)

**Comment by calebcartwright** [comment]
Need to get this done for a lot of the other items open right now. Going to go ahead and do it

**Comment by calebcartwright** [comment]
I hate this issue :(

**Comment by calebcartwright** [comment]
but I know how much it needs to be done
