### ISSUE TITLE
Add Angular project template

### ISSUE THREAD

**Issue by beverts312** [swellaby/generator-swell#55]

**Comment by calebcartwright** [comment]
agreed. I would propose angular 2 and/or angular 4. nowadays I see no reason to support any angularjs (ng 1) for a generator that is used to create net new projects

**Comment by beverts312** [comment]
@calebcartwright @marjorienorm Only a crazy person would still be using a generator that provided ng1x scaffolding ;)

**Comment by calebcartwright** [comment]
damn.. I didn't even think about it that way.. TRUTH!

**Comment by calebcartwright** [comment]
Looking to the folks that have worked with the new Angular versions ( @beverts312 @traviskosarek and maybe @skjr001) to help us figure out what this should look like

**Comment by calebcartwright** [comment]
Will also note that #109 will likely need to be done (at least partially) before this issue can be completely closed out due existing template/dependency content that is dropped by the generator. 

I assume the frontend project types like this will want to use something like jest, protractor, etc. for the testing ecosystem as opposed to being locked exclusively into the server-side mocha/chai/sinon testing config that exists today.

**Comment by calebcartwright** [comment]
No longer in scope given deprecation plans, refs #249
