### ISSUE TITLE
script to setup dev environment

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#62]
Thinking it would be good to have a script (preferably an npm script, otherwise sh & bat) to setup the development workspace

**Comment by beverts312** [comment]
agreed on the idea of the script  

Is your preference towards an npm script that there would only be one file?  
They main problem  I have with the npm script is it requires you to have `npm` (and some version of `node`) already installed (as apposed to having nothing already installed), I like the option to start from nothing.  
  
Other question, should we add an option to install VS Code? If they want/already have VS Code, should we install some extensions for them?

**Comment by calebcartwright** [comment]
posting our convo from earlier:

shell/bat/ps or whatever scripts for the ground up set up (someone that doesn't have git, node/npm, etc.) but part 2) should be an npm script (something like setup-dev: npm i -g yo)? Not sure if there are any "dev" deps outside of that that aren't already explicitly called out as dev-deps on the package itself.

Where and when possible should also leverage the npm post install hook

If it is possible/reasonable to install Code then sure. my guess is that might be tough on windows (msi right?) but why not

**Comment by beverts312** [comment]
yep got it we can definitely make it part of an npm script inoking other stuff

We can install that stuff easily windows using choclatey (I had forgotten about this gem until a few months ago). I don't want to force it on them (I mean I do, but you know) so I will make it an option

**Comment by calebcartwright** [comment]
@beverts312 is this still something we want for 1.0, and if so is the work being done on this [branch](https://github.com/swellaby/generator-swell/tree/dev-setup)?

**Comment by calebcartwright** [comment]
@beverts312 per our earlier discussion, I deleted the server side branch. I am going to remove this from the 1.0 release/milestone/project
