### ISSUE TITLE
Broken npm build script

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#64]
The npm build script is experiencing in inconsistent behavior that sometimes fails. The error appears to be caused whenthe eslint gulp task kicks off at the same time some of the unit test setup methods are starting. For some reason this results in the eslint task failing, and throwing an error which makes the tests error out.

Until recently this had only been observed on Linux but now appears to happen periodically on Windows as well.

**Comment by beverts312** [comment]
#65 fixes this on Linux and Windows (in testing on my machines)
I think the issue that we were seeing on Steve's machine is unrelated to this one I also cannot reproduce it on any of my machines. @calebcartwright Should we track that here, somewhere else or not at all?

**Comment by calebcartwright** [comment]
I think we should track that separately, especially since it seems like a different error. The core of this problem (eslint failure during certain gulp sequences) was the underlying focus of this issue so if that is fixed then lets close this out and follow the other in a new issue if needed
