### ISSUE TITLE
Hide transpiled files in VS Code

### ISSUE THREAD

**Issue by beverts312** [swellaby/generator-swell#68]
Steve showed me that you can hide the transpiled `*.js*` in VS Code

I want to verify that this does not impact the debugging experience and if it does not go a head and add this to our default vscode config for users.

@calebcartwright Thoughts/concerns?

**Comment by calebcartwright** [comment]
Does it blanket out all *js files or specificially the emitted ones from transpilation? If it's just emitted content then great (as long as it is easy to turn back on when needed for debugging purposes), but if it hides the gulpfile, gulp tasks, etc. then we should investigate some more

**Comment by beverts312** [comment]
you can use a glob pattern so we can hide specifically the ones emitted from transpilation
to reenable for debugging the user would just need to remove the line(s) from `.vscode/settings.json`, not sure if there is an easier toggle than that (will look into that)

**Comment by beverts312** [comment]
After some experimentation I have been unable to get to vscode to hit typescript breakpoints (regardless of sourceMap configuration). This settings should not be shipped with project types where this is the case. 

I think we should leave this open and I will do this only for the web types (angular/aurelia) since I have had better luck with the chrome debugger recognizings sourceMaps

**Comment by calebcartwright** [comment]
the thinking here is that we don't want to hide those files which are needed for debugging on the nodejs side?

**Comment by beverts312** [comment]
right, I wouldn't want to have to go delete those lines from my settings.json everytime I wanted to hit a breakpoint (maybe we could write an extension to make this a toggle button?)

**Comment by beverts312** [comment]
#78
