### ISSUE TITLE
Update docs for contribution to include generator version

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#74]
We should update the contribution docs to request users include the version of the generator itself when opening an issue (https://github.com/swellaby/generator-swell/blob/master/CONTRIBUTING.md#reporting-issues). 

Getting the version of a globally installed yeoman generator is unfortunately a little more complicated than a standard global module so we should also provide info, commands, or a script for users.

**Comment by beverts312** [comment]
@calebcartwright Did you find a command that worked? If not I will take this

**Comment by calebcartwright** [comment]
@beverts312 I was only able to find something that worked on Linux (and presumably Mac as well), but nothing universal. I can't imagine we're the first people to ever want to know the version of a specific yo generator, so I'm wondering if it would be beneficial to have this capability wrapped up in a separate utility (npm package?) that we can add to the swell generator (via dev dep?) but also package independently. 

thoughts?

**Comment by beverts312** [comment]
ooo I didnt even think about an npm package, that sounds like a good approach, I can take a stab at that package

**Comment by calebcartwright** [comment]
awesome. let me know if you want to put the repo in here (if you don't already have perms)

**Comment by beverts312** [comment]
Alrighty this package is ready to go (atleast to be invoked from node):  

- [npm](https://www.npmjs.com/package/get-pkg-version)
- [github](https://github.com/swellaby/get-package-version)  

We can talk next steps on slack and add it back here after for reference

**Comment by calebcartwright** [comment]
nice. I hadn't thought about the disconnect of the generated projects. lets hold off on adding it to generated projects for now
