### ISSUE TITLE
JSHint files still being scaffolded by the generator

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#75]
- node version: 7.7.2
- npm version: 4.1.2
- yeoman version: 1.8.5
- generator-swell version: 0.9.3-alpha
- OS: Windows 10

I just ran the generator and scaffolded a new VSTS Task project type, and somehow the jshint files (.jshintrc and .jshintignore) were added to the new project. I'm not really sure where it came from given the current codebase (and content of the files) but just want to ensure we didn't miss something when we removed jshint from the generator as part of #38.

Maybe it is coming from an extension on VS Code? @beverts312  have you seen this in any of your projects?

![image](https://cloud.githubusercontent.com/assets/13042488/23801215/f67c4f1c-0574-11e7-8af2-95509dda72ec.png)

**Comment by calebcartwright** [comment]
The plot thickens..

Just ran it again, but skipped the dependency install to keep the yo create output in context:

![image](https://cloud.githubusercontent.com/assets/13042488/23801566/350692fa-0576-11e7-9baf-eaa7f5e2edd4.png)

Note that the yo output does not include jshint content, and it shows in the generated project (no .jshint files this time):

![image](https://cloud.githubusercontent.com/assets/13042488/23801661/8e0375e4-0576-11e7-9225-351618b3dab5.png)

**Comment by calebcartwright** [comment]
Got it! The generated package.json file still has jshint as a dev dependency: https://github.com/swellaby/generator-swell/blob/master/generators/app/templates/boilerplate/package.json#L53 so as soon as an npm install is executed (either automatically by the generator or afterwards by the user), the default jshint files are created as a result. I'll fix this and merge it at some point in the future.

**Comment by beverts312** [comment]
@calebcartwright sorry for the delayed response, I have definitely been experiencing this

**Comment by calebcartwright** [comment]
lol it really confused the hell out of me at first. I've got this fixed now, just waiting to merge
