### ISSUE TITLE
Debugging TypeScript not working

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#76]
All platforms/versions

Steve has figured out why the debugging of TS on the node side isn't working (caused by a bug in the configuration of gulp-sourcemaps). Opening this issue to track that fix

**Comment by skjr001** [comment]
Just sent a pr your way.

**Comment by beverts312** [comment]
#78 (adding reference)

**Comment by beverts312** [comment]
@calebcartwright does this conflict with your changes?
