### ISSUE TITLE
New Feature: Extend git hook support

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#94]
Let's enhance the generator's support for adding git hooks to generated projects.  

- Have the first/initial prompt ask the user if they want to include git hook support in the project
  - This can either be a basic Confirm prompt type (y/n) or we could do a List prompt type with two options: one with text representing affirmation and another with text representing a decline (could introduce the cheeky message here)
- If affirmative, we should then present the user with options for the 3 core types of client side git hooks:
  - commit-msg
  - pre-commit
  - pre-push
- For those specific hooks, we could either:
 - (A) present each of those 3 as a Confirm prompt, and then plug in our own hook script for the respective hook type with a pre-coded default value
 - (B) present each of those 3 as a Confirm prompt, and then for each affirmative, present the user with a follow up List prompt that allows the user to pick which script/validation they'd like to run (for example lint, test, code coverage, etc.)
 - (C) present each of those 3 as a List prompt where the list contains the set of validation scripts we can plug in for that respective hook that make sense as well as a skip/ignore/don't setup the hook option. 

Here's an example of the prompt flow (with option A for the hook config):
`Would you like git hook support in your project? (y/n): y` (user affirms)
`Do you want me to add the commit-msg hook? (y/n): y` (user affirms)
`Do you want me to add the pre-commit hook? (y/n): y` (user affirms)
`Do you want me to add the pre-push hook? (y/n): n` (user declines)

And the generator would drop a husky file into the project that has the hooks setup with some default values for the hooks the user specified:
```json
hooks: {
   "commit-msg": "commitlint -e $GIT_PARAMS",
   "pre-commit": "npm run lint && npm test"
}
```

For option B the flow could look something like:
```
Would you like git hook support in your project? (y/n): y (user affirms)
Do you want me to add the commit-msg hook? (y/n): y (user affirms)
What would you like to run for your commit-msg hook? (list choice)
> commitlint (user selects commitlint option)
> foo
Do you want me to add the pre-commit hook? (y/n): y (user affirms)
What would you like to run for your pre-commit hook? (list choice)
> lint (user selects lint option)
> test
> lint and test
Do you want me to add the pre-push hook? (y/n): n (user declines)
```

And the generator would drop a husky file into the project that has the hooks setup with based on what the user specified:
```json
hooks: {
   "commit-msg": "commitlint -e $GIT_PARAMS",
   "pre-commit": "npm run lint"
}
```

For option C:
```
Would you like git hook support in your project? (y/n): y(user affirms)
What would you like to run for your commit-msg hook? (list choice)
> nothing
> commitlint (user selects commitlint option)
What would you like to run for your pre-commit hook?
> nothing
> lint
> test
> lint & test (user selects lint & test)
What would you like to run for your pre-pushhook?
> nothing (user selects nothing)
> lint
> test
> lint & test & coverage
``` 

And the generator would drop a husky file into the project that has the hooks setup with based on what the user specified:
```json
hooks: {
   "commit-msg": "commitlint -e $GIT_PARAMS",
   "pre-commit": "npm run lint && npm run test"
}
```

**Comment by calebcartwright** [comment]
really like the looks of this: https://www.npmjs.com/package/husky

**Comment by calebcartwright** [comment]
CC'ing @beverts312  and @traviskosarek Now that he is done conquering the Appalachain Trail

**Comment by calebcartwright** [comment]
We've been using husky elsewhere in other libs/repos, so I'm going to go ahead and plan on pulling that into the generator itself and generated projects unless there's any vehement disagreements

**Comment by beverts312** [comment]
I am pretty torn between `A` and `C`, I feel like the rest of the generator is kinda like "I dont really care you are gonna do it how I want" (option `A`), but I like the increased control (end-user perspective) with `C`

**Comment by calebcartwright** [comment]
Well said @beverts312 - I am leaning towards C too FWIW. I'd definitely agree generator in 1.x form is of the "My way" mindset, but I like option C here for the git hooks as I think our changes for 2.x (both planned and proposed) will provide the end-user much more flexibility

**Comment by traviskosarek** [comment]
I agree that C seems like the most versatile of the options for the user and I think that it is the best choice. That said, the generator self identifies as "highly opinionated" so I don't think any user would necessarily be upset that it chose what that script should be (option A).

I also like option C because it gets the user closer to what they specifically want as an end state of their project, which is what I think most users are looking for when deciding on scaffolding. Well... it is what they look for after "does it generate something that actually works", haha

**Comment by calebcartwright** [comment]
Also a good point @traviskosarek - Option C it is then! 

Our initial motivation for the generator was essentially to give us a new project that was already set up with capabilities for transpilation, linting, test execution, code coverage, etc. and back then we didn't really care how any of those capabilities were delivered (we were just tired of having to set them up manually)

I think we've all learned a lot since then though, and I believe that the goal for the 2.x version should be to not only simple provide those capabilities, but to do so in the exact way (or at least very very close) that the user wants

**Comment by calebcartwright** [comment]
No longer in scope given deprecation plans, refs #249
