### ISSUE TITLE
CI enhancement - CircleCI 2.x

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/generator-swell#97]
CircleCI (relatively) recently released the next major version of their platform. I think we should explore potentially updating our existing CircleCI config (1.x) to the new version, and perhaps see whether or not that would allow us to abandon Travis-CI (as opposed to using both of them like we do today)

https://circleci.com/features/ 
https://circleci.com/docs/2.0/ 
https://circleci.com/docs/2.0/migrating-from-1-2/

At the time I originally set the builds up, I was torn as CircleCI had some features I wanted that Travis-CI did not (test result tracking for one), and vice-versa (Travis-CI had a better set of integrations with other tools/platforms). 

My initial thoughts of what we would need to have in CircleCI  2.x to drop TravisCI:
- Sonarcloud integration
- Slack integration
- Codeclimate integration
- Coveralls integration
- Snyk integration
- Ability to run tests against multiple versions of node (i.e. via something like nvm)
- Ability to run tests against multiple platforms/distros (CircleCI 2x lets you bring your own Docker images for builds, whereas I believe TravisCI only allows you to choose between a couple versions of Ubuntu)

**** As a sidenote, I've opened up #98 to explore/consider using Appveyor so that we can have public CI builds for Windows too. The release pipeline in VSTS does run the same validation suite on Windows but I'd personally still like to use Appveyor in order to have publicly viewable builds, builds/comments on PRs, a Windows build gate for merges, etc. 

FYI - @skjr001 @marjorienorm @beverts312 @rucheeg in case anyone has thoughts/concerns/questions/etc. (especially if someone wants to take this one!)

(Edit) - Added the issue link for #98

**Comment by calebcartwright** [comment]
CC'ing @traviskosarek Now that he is done conquering the Appalachain Trail (and because no one else has weighed in)

**Comment by marjorienorm** [comment]
Welcome back Travis.  This is what I’m picturing 😊
[Image result for image of a bearded man]<https://www.bing.com/images/search?view=detailV2&ccid=Fn8HmzBp&id=AF7D53B0CAA2F8D2EDFF1071A88F32C14566A958&thid=OIP.Fn8HmzBp7DQGM5th1vEcewESEs&q=image+of+a+bearded+man&simid=608027127345971609&selectedIndex=25>

**Comment by traviskosarek** [comment]
Thanks @marjorienorm ! I'm back and coding with a vengeance!

Not quite the beard you were looking for, but I trimmed it back a ton.

![Image of me](https://scontent-atl3-1.cdninstagram.com/t51.2885-15/e35/21909492_116552789040758_2969099570191007744_n.jpg)
